### ISSUE TITLE
Error: "Must provide one of _form or _meta" with mongodb example

### ISSUE THREAD

**Issue by logsoft** [syrusakbary/Flask-SuperAdmin#144]
i was not able get an Collection hoocked to superadmin and tested the /examples/mongodb/simple.py but got the same error when trying to create or edit  :  "Must provide one of _form or _meta"
it seems to happen on collections/documents with linked content. not on single documents like "user"
reproducable on my machines with the plain /examples/mongodb/simple.py script

flask and extensions on latest pip packages
trace: http://pastebin.com/nYJJdGns

**Comment by logsoft** [comment]
ok i recognised that this is exactly this bug: https://github.com/syrusakbary/Flask-SuperAdmin/issues/138

**Comment by wojcikstefan** [comment]
Yup, WTForms >= 2.0 aren't supported yet. Perhaps we can close this issue now to not keep duplicates around?

**Comment by logsoft** [comment]
yeah pls close it then thx
